// generated by demolino

#ifndef __DEMO__
#define __DEMO__

int win_w = 320, win_h = 240;
void __tl_spt(long __t);
void __tl_tl_main(long __t);

void render()
{
	long __t = get_ticks();
	if (__t >= 0 && __t <= 8000) {
		long __rt = __t - 0;
		__tl_tl_main(__rt);
	}
}


void __tl_spt(long __t)
{
	if (__t >= 0 && __t <= 1000) {
		long __rt = __t - 0;
		draw_sphere(lirp(__t, 0, 1000, 4, 64), lirp(__t, 0, 1000, 4, 64));
	}
	if (__t >= 1000 && __t <= 2000) {
		long __rt = __t - 1000;
		draw_sphere(lirp(__t, 0, 1000, 64, 4), lirp(__t, 0, 1000, 64, 4));
	}
}

void __tl_tl_main(long __t)
{
	if (__t >= 0 && __t <= 2000) {
		long __rt = __t - 0;
		__tl_spt(__rt);
	}
	if (__t >= 2000 && __t <= 4000) {
		long __rt = __t - 2000;
		__tl_spt(__rt);
	}
	if (__t >= 4000 && __t <= 6000) {
		long __rt = __t - 4000;
		__tl_spt(__rt);
	}
	if (__t >= 6000 && __t <= 8000) {
		long __rt = __t - 6000;
		draw_sphere(lirp(__t, 0, 2000, lirp(__t, 0, 2000, 8, 10), 10), 16);
	}
}

#endif

